# Generated by Django 3.2.20 on 2023-07-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='created_user',
        ),
    ]
